import LinkedList.SinglyLinkedList.SinglyLinkedListPractice;

public class Main {



    public static void main(String[] args) {
        SinglyLinkedListPractice list = new SinglyLinkedListPractice();
//        list.display();
//        list.reverseLinkedList();
//        list.display();
//        list.findMiddleOfLinkedList();
//        list.display();
//        list.addLast(2);
//        list.display();
//        list.reverseLinkedList();
//        list.display();
//        list.findMiddleOfLinkedList();
//        list.display();
//        list.addLast(5);
//        list.findMiddleOfLinkedList();
//        list.display();
//        list.reverseLinkedList();
//        list.display();
//        list.addLast(9);
//        list.addLastRecursively(10);
//        list.addLast(7);
//        list.display();
//        list.isPalindrome();
//        list.display();
//        list.reverseLinkedList();
//        list.display();
//        list.findMiddleOfLinkedList();
//        list.addFirst(10);
//        list.reverseLinkedList();
//        list.display();
//        list.findMiddleOfLinkedList();
//        list.display();
//        list.deleteFirst();
//        list.display();
//        list.deleteFirst();
//        list.display();
//        list.deleteFirst();
//        list.display();
//        list.deleteFirst();
//        list.display();
//        list.deleteFirst();
//        list.display();
//        list.addFirst(10);
//        list.addLast(3);
//        list.addLast(8);
//        list.display();
//        list.deleteLast();
//        list.display();
//        list.deleteLast();
//        list.display();
//        list.deleteLast();
//        list.display();
//        list.deleteLast();
//        list.display();
//        list.deleteLast();
//        list.display();
//        list.deleteLast();
//        list.display();
//        list.isPalindrome();
//        list.addLast(10);
//        list.isPalindrome();
//        list.addLast(2);
//        list.addLast(10);
//        list.display();
//        list.isPalindrome();
        list.display();
        list.reverseLinkedListRecursively();
        list.display();
        list.addLast(10);
        list.display();
        //list.reverseLinkedListRecursively();
        list.display();
        list.addLast(2);
        list.display();
        //list.reverseLinkedListRecursively();
        list.display();
        list.addLast(5);
        list.addLast(9);
        list.addLast(10);
        list.addLast(7);
        list.display();
//        list.reverseLinkedListRecursively();
//        list.display();
//        list.addAtIndex(100,0);
//        list.addAtIndexRecursively(100,0);
//        list.display();
//        list.addAtIndex(200,-1);
//        list.addAtIndexRecursively(100,0);
//        list.display();
//        list.addAtIndex(300,10);
//        list.addAtIndexRecursively(100,0);
//        list.display();
//        list.addAtIndex(150,2);
//        list.addAtIndexRecursively(100,3);
//        list.display();
//        list.addAtIndex(250,4);
//        list.addAtIndexRecursively(100,5);
//        list.display();
//        list.addAtIndex(350,3);
//        list.addAtIndexRecursively(100,2);
//        list.display();
        list.addAtIndexRecursively(50,0);
        list.display();
        list.addAtIndexRecursively(150,3);
        list.display();
        list.addAtIndexRecursively(250,5);
        list.display();
    }
}